[2021-08-21 01:25:27,207] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2021-08-21T01:25:26.638183+00:00 [queued]>
[2021-08-21 01:25:27,228] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2021-08-21T01:25:26.638183+00:00 [queued]>
[2021-08-21 01:25:27,229] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:25:27,229] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-21 01:25:27,229] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:25:27,243] {taskinstance.py:1107} INFO - Executing <Task(PostgresOperator): creating_table> on 2021-08-21T01:25:26.638183+00:00
[2021-08-21 01:25:27,248] {standard_task_runner.py:52} INFO - Started process 11852 to run task
[2021-08-21 01:25:27,254] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'creating_table', '2021-08-21T01:25:26.638183+00:00', '--job-id', '28', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpw_yd4blc', '--error-file', '/tmp/tmpl6ft2g93']
[2021-08-21 01:25:27,254] {standard_task_runner.py:77} INFO - Job 28: Subtask creating_table
[2021-08-21 01:25:27,312] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.creating_table 2021-08-21T01:25:26.638183+00:00 [running]> on host 07cd8e03eca8
[2021-08-21 01:25:27,372] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=creating_table
AIRFLOW_CTX_EXECUTION_DATE=2021-08-21T01:25:26.638183+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-21T01:25:26.638183+00:00
[2021-08-21 01:25:27,373] {postgres.py:68} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
        
[2021-08-21 01:25:27,388] {base.py:78} INFO - Using connection to: id: db_pg. Host: postgres, Port: None, Schema: ***, Login: ***, Password: ***, extra: {}
[2021-08-21 01:25:27,394] {dbapi.py:204} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
        , parameters: None
[2021-08-21 01:25:27,395] {postgres.py:72} INFO - NOTICE:  relation "users" already exists, skipping

[2021-08-21 01:25:27,410] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=creating_table, execution_date=20210821T012526, start_date=20210821T012527, end_date=20210821T012527
[2021-08-21 01:25:27,452] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-21 01:25:27,462] {local_task_job.py:149} INFO - Task exited with return code 0
