[2021-08-21 01:20:34,691] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user 2021-08-21T01:19:27.502763+00:00 [queued]>
[2021-08-21 01:20:34,714] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user 2021-08-21T01:19:27.502763+00:00 [queued]>
[2021-08-21 01:20:34,714] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:20:34,714] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-21 01:20:34,714] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:20:34,727] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): storing_user> on 2021-08-21T01:19:27.502763+00:00
[2021-08-21 01:20:34,732] {standard_task_runner.py:52} INFO - Started process 11196 to run task
[2021-08-21 01:20:34,737] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'storing_user', '2021-08-21T01:19:27.502763+00:00', '--job-id', '17', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpefeazt13', '--error-file', '/tmp/tmp6ytb_ebj']
[2021-08-21 01:20:34,738] {standard_task_runner.py:77} INFO - Job 17: Subtask storing_user
[2021-08-21 01:20:34,792] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.storing_user 2021-08-21T01:19:27.502763+00:00 [running]> on host 07cd8e03eca8
[2021-08-21 01:20:34,860] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=storing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-08-21T01:19:27.502763+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-21T01:19:27.502763+00:00
[2021-08-21 01:20:34,861] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-21 01:20:34,861] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'psql postgresql://***:***@postgres/*** -c "\\copy users FROM \'/tmp/processed_user.csv\' delimiter \',\' csv"']
[2021-08-21 01:20:34,873] {subprocess.py:74} INFO - Output:
[2021-08-21 01:20:34,919] {subprocess.py:78} INFO - ERROR:  duplicate key value violates unique constraint "users_pkey"
[2021-08-21 01:20:34,919] {subprocess.py:78} INFO - DETAIL:  Key (email)=(email) already exists.
[2021-08-21 01:20:34,919] {subprocess.py:78} INFO - CONTEXT:  COPY users, line 1
[2021-08-21 01:20:34,920] {subprocess.py:82} INFO - Command exited with return code 1
[2021-08-21 01:20:34,933] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-08-21 01:20:34,935] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=user_processing, task_id=storing_user, execution_date=20210821T011927, start_date=20210821T012034, end_date=20210821T012034
[2021-08-21 01:20:34,986] {local_task_job.py:149} INFO - Task exited with return code 1
